server.port=9123
#spring.datasource.url=jdbc:postgresql://localhost:5432/mbis_dev
#spring.datasource.username=postgres
#spring.datasource.password=postgres

spring.datasource.url=jdbc:postgresql://10.100.20.53:5432/mbis_dev
spring.datasource.username=postgres
spring.datasource.password=askrindo

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE




agent.host.url = http://fajris-mac-mini.tail2fab46.ts.net:11434/api/chat
ai.model.picture=qwen3-vl:4b
prompt.user.picture=Extract ONLY explicit field-value relevant pairs which is still empty. And Return ONLY WITH JSON.
system.feedback.picture=You extract structured data from image. Only return valid JSON array. No explanation.

ai.model.base.knowledge=qwen2.5:1.5b
ai.model.context.base.knowledge=32000
ai.context.max.prompt.words=200