server.port=9123
spring.datasource.url=jdbc:postgresql://localhost:5432/mbis_dev
spring.datasource.username=postgres
spring.datasource.password=postgres

#spring.datasource.url=jdbc:postgresql://10.100.20.53:5432/mbis_dev
#spring.datasource.username=postgres
#spring.datasource.password=askrindo

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
