server.port=9123
spring.datasource.url=jdbc:postgresql://localhost:5432/mbis_dev
spring.datasource.username=postgres
spring.datasource.password=postgres

#spring.datasource.url=jdbc:postgresql://10.100.20.53:5432/mbis_dev
#spring.datasource.username=postgres
#spring.datasource.password=askrindo

#spring.datasource.url=jdbc:postgresql://10.100.20.111:5434/askrindoauth
#spring.datasource.username=app_reas
#spring.datasource.password=askrindo123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

output.ai.folder=C:\\Users\\alfaj\\workspace\\mbis\\be-mbis-ai-migration\\src\\main\\resources\\files
output.ai.folder.excel=C:\\Users\\alfaj\\workspace\\mbis\\be-mbis-ai-migration\\src\\main\\resources\\excel
agent.host.url.image = http://fajris-mac-mini.tail2fab46.ts.net:11434/api/chat
agent.host.url.generate.text = http://fajris-mac-mini.tail2fab46.ts.net:11434/api/generate
agent.host.url.chat.text = http://fajris-mac-mini.tail2fab46.ts.net:11434/api/chat

ai.model.picture=qwen3-vl:4b
ai.model.context.base.picture=32000

ai.model.base.knowledge=mistral:7b
ai.model.context.base.knowledge.max=32000
ai.model.context.base.knowledge.use=1000
ai.model.data.crawl.limit=1